### ISSUE TITLE
Monitor Series

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/telegram-sonarr-bot#1]
Create a new switch for monitoring the series, and have the options be:

1) Future 2) All 3) None 4) Latest Season

`/m [n]` to continue...

**Comment by subzero79** [comment]
I am about to suggest in sonarr an option to monitor the first episode only. Some series are released in a lot of episodes in the same day like netflix or amazon productions. Sometimes i like to watch the first episode only to see if i like it or not, then decide to monitor the rest and fire a search missing

**Comment by onedr0p** [comment]
Instead of first episode, would first season be better?

**Comment by onedr0p** [comment]
Added in latest version.
