### ISSUE TITLE
Unable to add new Series (Profile bug)

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/telegram-sonarr-bot#12]
I'll leave this here. I am adding the series Angry Beavers and I have 2 Profiles set up SD and HD, when I select one and finish it says the series was added but it wasn't and there is an error in Sonarr logs saying:

```
Invalid request Validation failed: 
 -- Profile does not exist
```

If I get time I'll work on a fix.

**Comment by jayrox** [comment]
this sounds like the ID of the profile may be incorrect. add a console.log to the profile id and compare it to a console.log of the profile list and make sure the ids match.

**Comment by onedr0p** [comment]
got it resolved woooo
