### ISSUE TITLE
Oh no! Error

### ISSUE THREAD

**Issue by M0UL** [onedr0p/telegram-sonarr-bot#24]
i am seeing this  Oh no! Error: Only the admin can use this feature, every time i try to use admin command. any way to fix this? 

i am using the docker version

**Comment by onedr0p** [comment]
Did you make sure you set the bot owner flag to your telegram userid?

**Comment by M0UL** [comment]
i think i have done tham but i am not really sure how to see if i set the right id, where can i find my telegram id again?

**Comment by onedr0p** [comment]
Interesting, I'll take a look and see what could be going wrong here.

**Comment by onedr0p** [comment]
There has to be a problem with your telegram user id, other users aren't reporting back with this issue.

**Comment by onedr0p** [comment]
Any update? I'll close this issue in a couple days if you don't respond :)
