### ISSUE TITLE
Please select from the menu below issue

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#25]
When searching for a new series its possible you want to know if the given series is the one you search, you press the link, but than the 'select from the menu below' is not there anymore
you have to restart the search again

**Comment by onedr0p** [comment]
You are saying the keyboard disappears when you open the link?

**Comment by aroundmyroom** [comment]
official telegram app iphone
ie, i enter /q game
list of series is returned, 
under this list I can enter commands and under that list I can press the series I want to add

when I click the link of a series the info of the tvdb is opened. When I have read the info of the series I select in the upper left: finished
I return to the chat but now the selection I can make (lower part of the screen) is gone, only the chat (returned TV series and the input box for command is present).

This means that after getting additional information of a tv series you need to re-search for that tv series to reselect.

**Comment by onedr0p** [comment]
I'll take a look and see if theres anything i can do to fix the issue.

**Comment by onedr0p** [comment]
I looks like maybe its a iPhone issue, when you return back to the Telegram App do  you see a icon that has 4 squares in it next to the send button? If so, click that and you can see the options again.

**Comment by aroundmyroom** [comment]
Indeed, there is a 4 square option, issue resolved :/)

Verstuurd vanaf mijn iPhone

**Comment by onedr0p** [comment]
hah great, just pushed a few updates too! enjoy :)
