### ISSUE TITLE
adding help?

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#28]
something like this?

/*
 * handle help command
 */

bot.onText(/\/help/, function(msg) {
  var fromId = msg.from.id;

  verifyUser(fromId);

  logger.info('user: %s, message: sent \'/help\' command', fromId);

  var response = ['Hello ' + getTelegramName(msg.from) + ', you asked for help'];
  response.push('\n`/start to start his bot` \n `/second command`\n`/q [series name]`\n`/upcoming shows upcoming episodes, has a day parameter, defaults to 3 days`\n`/clear clear all previous comm$

  bot.sendMessage(fromId, response.join('\n'), { 'parse_mode': 'Markdown', 'selective': 2 });
});

**Comment by onedr0p** [comment]
Looks good, I'll add a help command in the next release.

**Comment by onedr0p** [comment]
Added in latest commit.
