### ISSUE TITLE
Add custom keyboards

### ISSUE THREAD

**Issue by subzero79** [onedr0p/telegram-sonarr-bot#3]
To avoid the typing, telegram provides custom keyboards to display the possible choices.

https://core.telegram.org/bots#keyboards

![a1ee46a377796c3961](https://cloud.githubusercontent.com/assets/7058119/11764115/35f8a052-a16f-11e5-86cd-5078751c8ab2.jpg)

**Comment by onedr0p** [comment]
I'll keep this issue open as a constant reminder. Maybe Telegram will make this a bit easier on the backend in the future.

**Comment by kstanleyadams** [comment]
Please could you elaborate on the limitations that caused you to remove this feature?

**Comment by onedr0p** [comment]
@kstanleyadams 

Some options may include a lot of options to choose, for example quality profiles or series to choose.

Also, in order to use this selection functionality we would need to include the TVDB ID in the selection boxes and it just doesn't look neat. See [here](https://github.com/onedr0p/telegram-couchpotato-bot/blob/312ec3d51019027667fab727d9456a24ed1c4358/Readme.md) for how it was done previously.

**Comment by kstanleyadams** [comment]
How many keyboard options is too many? Does it just look crowded/ugly or is there an upper limit?

If the keyboard entry isn't feasible, I wonder if it is worth implementing a more context aware input, where the "/" commands can be omitted, and only the number is entered? It is quite tedious typing it all.

e.g.
/q Game of Thrones
1 
1
1
1

This is much easier than:

/q Game of Thrones
/s 1 
/p 1
/f 1
/m 1

**Comment by onedr0p** [comment]
There's switches to have the app understand what step the user is inputting. If it was simply '1' the app wouldn't know what step you are on.

**Comment by kstanleyadams** [comment]
Sorry I'm not familiar with how the telegram API and backend work. Is it not possible to infer the switch based on the context, and then accept the input accordingly?

**Comment by onedr0p** [comment]
Hm, maybe but coding it that way would be way more effort than its worth. The way it is now makes sense to have a workflow to add a certain item via switches. If you take a look at the code maybe it will make more sense to you. Each switch runs a task via the sonarr API.

**Comment by onedr0p** [comment]
> How many keyboard options is too many? Does it just look crowded/ugly or is there an upper limit?

The options do look crowded.

I'll take a look at this in the future, for now it's fine. You won't be adding a million series thru this at one time.

**Comment by jayrox** [comment]
i submitted PR #8 that should resolve this issue.
