### ISSUE TITLE
Request: add 'series' command to show series in Sonarr

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#30]
I have no knowledge of js, but I was playing with the sonarr.js yesterday and added the quircky help and tried to add the 'series' api command to get all my shows displayed 

One of the reasons I want to display all my shows is that sometimes people ask me what I have and what is nice to see. I dunno all by name as I have around 197 series in Sonarr (yep, crazy I know)

So the /series command would give me all my shows but it crashed due to too many data or something like that.

Achievable?

**Comment by onedr0p** [comment]
This would be nice but there is a text limit on how many characters can be in a message. I could add a command to search the sonarr library like `/series [show name]`.

**Comment by onedr0p** [comment]
I added a `/library` command to search your sonarr library in [this](https://github.com/onedr0p/telegram-sonarr-bot/commit/823aba58be4c4f1709c8360138593e87899582d0#diff-c578dcea0c50c42f9e339e093d8a28d3R394) commit.

**Comment by aroundmyroom** [comment]
library command does work, only I see the npm needs fs-extra now without that no start ;-)

**Comment by onedr0p** [comment]
whoops, yep. DO you think this is alright to close? or would you still like to see all series returned?

**Comment by aroundmyroom** [comment]
maybe for the /series you can chunck the message up in x messages?

see here example of a commit where the message is split ?
https://github.com/lukefx/hubot-telegram/commit/1358c047e6c72d5a7717b19edbcab430e9d075d4

**Comment by onedr0p** [comment]
The tricky part would be to make sure the series titles aren't cut off when sending multiple messages.

**Comment by onedr0p** [comment]
I think I figured it out.. In the latest commit `/library` returns all series.

**Comment by aroundmyroom** [comment]
if there is a way to trick the sorting .. 

the first message starts with:
The originals ends with iZombie
2nd: Rosewood ends with The Odd Couple
3rd: Homeland - Rogue
4rd: 12 Monkies - Heroes reborn

4 should be 1
3 should be 2
2 should be 3
1 should be 4

 But already happy with this result !

**Comment by aroundmyroom** [comment]
tested with my unknown experience how to code
do not use line 423 but put it a little lower with maybe a reverse?

  //  response.sort();

      if (query) {
        // add title to begining of the array
        response.unshift('*Found matching results in Sonarr library:*');
      }

      response.sort().reverse();

This gives me my 197 series in sorted order 
from
12 Monkeys to Covert Affairs
2nd message from Crazy Ex-Girlfriend to Odyssey
3rd message from Of kings and Prophets to The 100
4rd message from The Affair to iZombie

w00t ;-)

**Comment by onedr0p** [comment]
Weird, it comes back in A-Z for me.

**Comment by aroundmyroom** [comment]
phew ;-)

**Comment by onedr0p** [comment]
Very strange the array is sorted fine in the code, but when it sends it gets out of order. I am unsure why this is happening. I'll open a new issue for this.
