### ISSUE TITLE
/library command sends messages in incorrect order.

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/telegram-sonarr-bot#31]
The messages are split based on length using lodash `Array.chunk` method, the bot sends the messages in incorrect order and not `# A-Z`.

**Comment by jayrox** [comment]
I did some testing with this and it looks like the bot is sending the messages too fast and telegram just grabs and sends in which ever order it wants. When I added a `console.log(n);` it caused the bot to delay in sending the message just long enough for telegram to send the messages in the correct order.
Maybe a short timer in the loop will fix the bug.

**Comment by aroundmyroom** [comment]
Would like to test this idea . .where to put it, As I am the one reporting it ;-)

**Comment by aroundmyroom** [comment]
I could test this tonight If I now where to place it ..

**Comment by jayrox** [comment]
modules/SonarrMessage.js
line 74

**Comment by aroundmyroom** [comment]
nope .. 
before and after the  sort .. no go . .the log in my shell is ok, perfect sorted, but the messages itself in telegram not

     _.forEach(splitReponse, function(n) {
       n.sort();
       console.log(n);

**Comment by aroundmyroom** [comment]
changed it a little bit

 setTimeout(function() {
      console.log(n);
      }, 10000);

but the messages appear earlier in Telegram than that the output is on the screen, tells me that it probably is incorrect place ..

**Comment by jayrox** [comment]
I just commit a fix that Works For Me™

I replaced the for-loop with a 200ms setInterval. This adds the needed delay to send the messages in the correct order. It's not as pretty as the rest of @onedr0p's code but i'll be damned if it doesn't get the job done.

**Comment by onedr0p** [comment]
Interesting way of doing it, as long as it gets the job done it fine with me :)

**Comment by jayrox** [comment]
Sometimes you just got to get creative.

**Comment by aroundmyroom** [comment]
let me check it

**Comment by aroundmyroom** [comment]
i got 4 messages in correct order .. 
started it 2 times and it kept in this way
so .. works for me 2 . .great !!

**Comment by aroundmyroom** [comment]
btw used this nice tool already 4 or 5 times adding new shows .. works great !

**Comment by jayrox** [comment]
awesome! going to go ahead and close this one
