### ISSUE TITLE
(Username) undefined has been granted access.

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/telegram-sonarr-bot#32]
Noticed that undefined is in the text to the bot owner when someone authenticates.

**Comment by onedr0p** [comment]
This probably applies to the CP bot too.

**Comment by onedr0p** [comment]
From what I can tell is that Undefined comes from the last name not being set by the user. Need a check for that.

**Comment by jayrox** [comment]
i thought this should have been resolved with:

```
/*
 * get telegram name
 */
function getTelegramName(user) {
   return user.username || (user.first_name + (' ' + user.last_name || ''));
}
```

**Comment by onedr0p** [comment]
I don't why I am seeing it then maybe undefined is a string?

**Comment by jayrox** [comment]
try adding a console.log to username, first_name and last_name and see what they are returning?

**Comment by onedr0p** [comment]
I'll get back to this in a few days, busy with work :/

**Comment by onedr0p** [comment]
closing this now, I have no idea and I can't replicate this now.. wth!

**Comment by jayrox** [comment]
ha!
