### ISSUE TITLE
all monitored bug

### ISSUE THREAD

**Issue by M0UL** [onedr0p/telegram-sonarr-bot#35]
when i added show with to bot to sonarr, i told the both to monitor all episodes. when i came back to sonarr, nono of the episodes where monitored.

**Comment by aroundmyroom** [comment]
What show and what does Sonarr return if you search manually?

**Comment by onedr0p** [comment]
Also, if you could post logs for that it would be helpful!

**Comment by M0UL** [comment]
i added a few anime, all of those happend the same. 
i am running in docker on a synology

docker log: https://dl.dropboxusercontent.com/u/1781605/telegram-sonarr-bot.html
sonarr log: https://dl.dropboxusercontent.com/u/1781605/nzbdrone.1.txt

**Comment by onedr0p** [comment]
I see where the problem may lie. I'll have a fix tonight. Thanks!

**Comment by onedr0p** [comment]
fixed in latest commit!
