### ISSUE TITLE
grab on download etc.

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#36]
Is it possible to extend the functionality of the script by telling Telegram bot what series have been grabbed, downloaded etc?

**Comment by aroundmyroom** [comment]
update. I have shell script in place now which runs as custom script and announces it to the same bot

**Comment by jayrox** [comment]
mind sharing what you setup?

**Comment by aroundmyroom** [comment]
Hi Jayrox,
Here is the thread on the sonarr forum
https://forums.sonarr.tv/t/notification-to-telegram-im/9039/3

**Comment by onedr0p** [comment]
Looks good, I am unsure that we can build this directly into the bot. I think it needs to be a separate script like you linked.

In my case I use PlexPy with Plex and have a bot to notify a group of people of new releases.

**Comment by aroundmyroom** [comment]
Yeah I was thinking to provide a 2nd python script which can be hooked upon this one as the settings are already there ;-)

**Comment by onedr0p** [comment]
I created a test nodejs script to hook into sonarr, you can add it into sonarr.

`Settings` > `Custom Scripts` > `Path`: `node sonarr_notify.js`

sonarr_notify.js
```js
'use strict';

var TelegramBot = require('node-telegram-bot-api');

var options = { polling: false };

var token = process.env.TELEGRAM_BOT_TOKEN || 'YOUR_BOT_TOKEN';
var bot = new TelegramBot(token, options);

var groupId = YOUR_GROUP_OR_USER_ID;

var episode = process.env.sonarr_episodefile_relativepath || 'Unknown Episode';
var quality = process.env.sonarr_episodefile_quality || 'Unknown Quality';

var regex = /^[^\/]*\/(.*)\.(avi|mp4|mkv)/gi;

if (episode.match(regex)) {
	episode = episode.replace(regex, '$1');
}

bot.sendMessage(groupId, 'Downloaded ' + episode + ' (' + quality + ')');
```

I haven't tested it but I'm sure it works ^_^

**Comment by aroundmyroom** [comment]
node script is working in the shell but is lacking info ;)
I want to know the source and destination and the size .. 
will test it as custom script

**Comment by onedr0p** [comment]
Using the node script would be better because not everyone is on linux :) Anything can be changed there to fit your need.

**Comment by aroundmyroom** [comment]
node sonarr_notify.js 
is not working at the path as it will fail the existence
/home/to/whatever/node notification.js is what I am trying now but . .mmm ..

**Comment by onedr0p** [comment]
Drop the script into the same directory as the bot because it requires `require('node-telegram-bot-api');`

**Comment by jayrox** [comment]
you could probably tell it to load the config and get the `YOUR_GROUP_OR_OWNER_ID` from the `config.app.owner` field

**Comment by aroundmyroom** [comment]
onedr0p it is
but i made stupid error
path is now 
/usr/bin/nodejs 
arguments with: /home/user/Telegram/notification.js
now testing ..

**Comment by aroundmyroom** [comment]
ah that is working
Downloaded CSI- Cyber - S02E12 - HDTV - 720p Dimension (HDTV-720p)

**Comment by onedr0p** [comment]
@jayrox that's the idea. We would need a new field in the config.json called notifyTo or something seeing as we can using groupIds or userIds

**Comment by jayrox** [comment]
totally, i don't see any reason why we couldnt add that.

**Comment by aroundmyroom** [comment]
ok basis script tested and working . can be used and expanded ;-)
my config is working and can be used as test mule ..

**Comment by onedr0p** [comment]
@aroundmyroom awesome! I'll get this script added to teh repo tonight. if you want customize it a bit and get back to me with your changes.

**Comment by aroundmyroom** [comment]
ahahah /me no no at node js, but I can use some logic .. let me play a bit with billions playing next to me just after I watched an awesome Shameless ..

**Comment by jayrox** [comment]
its ok if you dont know node.js, if you have an idea but arent sure how to implement it let us know im sure we can figure something out.

**Comment by jayrox** [comment]
so when we add the notifyTo or whatever do we want to go ahead and change all of the notifications used else where that send to the owner currently?

**Comment by aroundmyroom** [comment]
```
var episode = process.env.sonarr_episodefile_relativepath || 'Unknown Episode';
var quality = process.env.sonarr_episodefile_quality || 'Unknown Quality';
var source  = process.env.sonarr_episodefile_scenename || 'Unknown Name';
var target  = process.env.sonarr_episodefile_path || 'Unknown path';

var regex = /^[^\/]*\/(.*)\.(avi|mp4|mkv)/gi;

if (episode.match(regex)) {
    episode = episode.replace(regex, '$1');
}

bot.sendMessage(groupId, 'Episode Imported ' + 'Source: ' + source + '|' + 'MB ' + 'Destination: ' + target);

```
we need some 'carriage returns' to get it on a next line.. 

the size can be taken from

(shell example, no idea how to get it in nodejs)

size=$(stat -c "%s" "$sonarr_episodefile_path")
sizeMb=$( expr $size / 1048576 )

**Comment by jayrox** [comment]
node.js function to get filesize:

```
var fs = require("fs");
function getFilesizeInBytes(filename) {
  var stats = fs.statSync(filename)
  var fileSizeInBytes = stats["size"]
  return fileSizeInBytes
}
```

**Comment by aroundmyroom** [comment]
my example is working it gives now

Episode Imported Source: CSO.Cyber.S02E12.720p.HDTV.X264-DIMENSION|MB Destination: /media/usenet/TV/CSI Cyber/Season 2/CSI-Cyber - S02E12 - HDTV - 720p - DIMENSION.mkv ..

need some adjusment at the |MB part and the returns .. further ok
How to do bold?

**Comment by jayrox** [comment]
add two * around it like this: `**bold**`

**Comment by aroundmyroom** [comment]
mmm thats not working when testing 

bot.sendMessage(groupId, '**Episode Imported**\n' + '**Source:** ' + source + ' | ' + 'MB \n' + '**Destination:** ' + target);

I get ** in my Telegram when testing from shell

**Comment by jayrox** [comment]
ahh yea, you need to send options with it, one sec

**Comment by jayrox** [comment]
try this:

```
bot.sendMessage(groupId, '**Episode Imported**\n' + '**Source:** ' + source + ' | ' + 'MB \n' + '**Destination:** ' + target, {
      'disable_web_page_preview': true,
      'parse_mode': 'Markdown',
      'selective': 2,
    });
```

**Comment by aroundmyroom** [comment]
that gives me the output without bold

**Comment by onedr0p** [comment]
Bold is single `*` if I'm not mistaken.

**Comment by aroundmyroom** [comment]
solution, use one * ;-)

**Comment by aroundmyroom** [comment]
so the code (without MB still) is
`var episode = process.env.sonarr_episodefile_relativepath || 'Unknown Episode';
var quality = process.env.sonarr_episodefile_quality || 'Unknown Quality';
var source  = process.env.sonarr_episodefile_scenename || 'Unknown Name';
var target  = process.env.sonarr_episodefile_path || 'Unknown path';

var regex = /^[^\/]*\/(.*)\.(avi|mp4|mkv)/gi;

if (episode.match(regex)) {
    episode = episode.replace(regex, '$1');
}

bot.sendMessage(groupId, '*Episode Imported*\n' + '*Source:* ' + source + ' | ' + 'MB \n' + '*Destination:* ' + target, {
      'disable_web_page_preview': true,
      'parse_mode': 'Markdown',
      'selective': 2,
    });
`

**Comment by jayrox** [comment]
to make it a little bit easier to read and maintain, how about something like this:

```
var message = [];
message.push('*Episode Imported*');
message.push('*Source:* ' + source);
message.push('*Size:*' + 'sizehere' + 'MB');
message.push('*Destination:* ' + target);

bot.sendMessage(groupId, message.join('\n'), {
  'disable_web_page_preview': true,
  'parse_mode': 'Markdown',
  'selective': 2,
});
```

**Comment by onedr0p** [comment]
Looks good guys. I'll definitely add this to the repo tonight with instructions and the updates.

**Comment by aroundmyroom** [comment]
let me try that one

**Comment by aroundmyroom** [comment]
aiii
/Telegram/notification.js:14
message.push('*Source:* ' + source);
                            ^

ReferenceError: source is not defined
    at Object.<anonymous> (/home/dennis/Telegram/notification.js:14:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by aroundmyroom** [comment]
oh damn
lol .. removed my vars

**Comment by aroundmyroom** [comment]
code is working flawlessly through Sonarr ..

**Comment by jayrox** [comment]
awesome, what about the file size part? i left a placeholder with 'sizehere'.

**Comment by aroundmyroom** [comment]
if I could embed the function part .. but that is yeah . .a grey dark hole called: dunno how to do that

**Comment by onedr0p** [comment]
Here shows you all the available sonarr varaibles.
https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts

You will want to use `process.env.sonarr_episodefile_path`

```js
var fs = require("fs");

var target  = process.env.sonarr_episodefile_path || 'Unknown path';

var stats = fs.statSync(target)
var fileSizeInMegaBytes = stats["size"]  / 1048576

```

**Comment by aroundmyroom** [comment]
uhm.. missing some stuff 

```
root@media:/home/dennis/Telegram# nodejs notification.js
fs.js:892
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'Unknown path'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at Object.<anonymous> (/home/dennis/Telegram/notification.js:18:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

```

**Comment by onedr0p** [comment]
Looks like it is not finding the path. `Error: ENOENT: no such file or directory, stat 'Unknown path'`

**Comment by aroundmyroom** [comment]
oh .. ok ..uhm. no path due to entering it in shell let me try through sonar..

**Comment by onedr0p** [comment]
We may want to leave the size out, because what if the path is on a remote machine? Size isn't that important to send to the user or group.

**Comment by jayrox** [comment]
I agree, kill the line. I know I don't personally care about file sizes.

**Comment by aroundmyroom** [comment]
Thought it would be nice ;-)

**Comment by jayrox** [comment]
It would be nice, for sure. I'll play around with it a bit tonight before I totally discount it.

**Comment by onedr0p** [comment]
Either way is fine, I'll include it in the code. But I am unsure how it will work for remote libraries.

**Comment by aroundmyroom** [comment]
;-) it's 23.00PM here, So am almost closing for tonight. I am testing 1 last setup and see if the size is coming .. in first test not.
it does not matter, but I thought if it can be done in shell it should be possible in nodejs ;-)

Wahhhh

this code works with size ;-)


```
var episode = process.env.sonarr_episodefile_relativepath || 'Unknown Episode';
var quality = process.env.sonarr_episodefile_quality || 'Unknown Quality';
var source  = process.env.sonarr_episodefile_scenename || 'Unknown Name';

var fs = require("fs");
var target  = process.env.sonarr_episodefile_path || 'Unknown path';

var stats = fs.statSync(target)
var fileSizeInMegaBytes = stats["size"]  / 1048576

var message = [];
message.push('*Episode Imported*');
message.push('*Source:* ' + source);
message.push('*Size:*' + size + 'MB');
message.push('*Destination:* ' + target);

bot.sendMessage(groupId, message.join('\n'), {
  'disable_web_page_preview': true,
  'parse_mode': 'Markdown',
  'selective': 2,
});

```

**Comment by jayrox** [comment]
We can check the results from stats and see if the size is available and use it if it is or catch the error otherwise

**Comment by onedr0p** [comment]
Yep, that would be the best.

**Comment by aroundmyroom** [comment]
I've just removed the filesize part in de code and called it the day ;-) see the results tomorrow ;-)

**Comment by onedr0p** [comment]
I put the final code below.

TODO:
Try/catch on filzesize
Config update to set notifyId

```js
'use strict';
var fs = require('fs');
var TelegramBot = require('node-telegram-bot-api');

var config = require(__dirname + '/lib/config');

var bot = new TelegramBot(config.telegram.botToken, { polling: false });

var groupId = config.bot.notifyId;

var episode = process.env.sonarr_episodefile_relativepath || 'Unknown Episode';
var quality = process.env.sonarr_episodefile_quality || 'Unknown Quality';
var source  = process.env.sonarr_episodefile_scenename || 'Unknown Name';
var target  = process.env.sonarr_episodefile_path || 'Unknown path';

var stats = fs.statSync(target)
var fileSizeInMegaBytes = stats['size']  / 1048576

var message = [];
message.push('*Episode Imported*');
message.push('*Source:* ' + source);
message.push('*Size:*' + 'size' + 'MB');
message.push('*Destination:* ' + target);

bot.sendMessage(groupId, message.join('\n'), {
  'disable_web_page_preview': true,
  'parse_mode': 'Markdown',
  'selective': 2,
});
```

**Comment by jayrox** [comment]
I've been messing with this quite a bit, looks awesome. I've set up a group chat with a couple people and was struggling with finding the group chat id. turns out its the id in the URL with the `g` swapped out with a `-` for example: `https://web.telegram.org/#/im?p=g108092135` the group chat id is  `-108092135`

I'm not certain that this is the rule but that's what I've found so far.

**Comment by aroundmyroom** [comment]
@onedr0p where in your code is the chatid ? cause I get this error in sonarr .. 

16-2-2 20:44:37.5|Error|nodejs|Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: chat_id is empty"}
16-2-2 20:44:37.5|Error|nodejs|    at /home/dennis/Telegram/node_modules/node-telegram-bot-api/src/telegram.js:111:15
16-2-2 20:44:37.5|Error|nodejs|    at tryCatcher (/home/dennis/Telegram/node_modules/bluebird/js/main/util.js:26:23)
16-2-2 20:44:37.6|Error|nodejs|    at Promise._settlePromiseFromHandler (/home/dennis/Telegram/node_modules/bluebird/js/main/promise.js:507:31)
16-2-2 20:44:37.6|Error|nodejs|    at Promise._settlePromiseAt (/home/dennis/Telegram/node_modules/bluebird/js/main/promise.js:581:18)
16-2-2 20:44:37.6|Error|nodejs|    at Promise._settlePromises (/home/dennis/Telegram/node_modules/bluebird/js/main/promise.js:697:14)
16-2-2 20:44:37.7|Error|nodejs|    at Async._drainQueue (/home/dennis/Telegram/node_modules/bluebird/js/main/async.js:123:16)
16-2-2 20:44:37.7|Error|nodejs|    at Async._drainQueues (/home/dennis/Telegram/node_modules/bluebird/js/main/async.js:133:10)
16-2-2 20:44:37.7|Error|nodejs|    at Immediate.Async.drainQueues [as _onImmediate] (/home/dennis/Telegram/node_modules/bluebird/js/main/async.js:15:14)
16-2-2 20:44:37.8|Error|nodejs|    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by onedr0p** [comment]
ChatID / GroupId will come from a value in the config file that isn't there yet.

I'll get to adding this to the repo when I have free time today. I've been swamp with work.

**Comment by aroundmyroom** [comment]
work? what is that? ;-)

**Comment by jayrox** [comment]
i got this all added to my local install last night. i was unable to get sonarr to send an actual notification which is why i haven't commit the code yet at this time. manually calling the script works but nothing from sonarr. i'll dig into it a bit more tonight and see if i can figure out why its not sending anything

**Comment by jayrox** [comment]
@aroundmyroom see my [comment ](https://github.com/onedr0p/telegram-sonarr-bot/issues/36#issuecomment-178354167) on how to get to chatid

**Comment by onedr0p** [comment]
> i got this all added to my local install last night. i was unable to get sonarr to send an actual notification which is why i haven't commit the code yet at this time. manually calling the script works but nothing from sonarr. i'll dig into it a bit more tonight and see if i can figure out why its not sending anything

did you try using the full path to node executable?

**Comment by jayrox** [comment]
yea, sure did. have the full path to node in the path and the full path to the notify_sonarr.js in the arguments

**Comment by onedr0p** [comment]
interesting, @aroundmyroom  was able to get it to work. maybe he can shed some light on what's required on the sonarr custom script textboxes

**Comment by jayrox** [comment]
i added some logging and it didnt seem to even print. i wonder if its a windows issue. i fell asleep before i got too deep into having it write to a log file.

**Comment by aroundmyroom** [comment]
The following is what I have noticed with the custom script in sonarr
and yes it took me some hours to get a working script  due to some silly issue .. 

Please bear with me that this is what I use to get it working. It could be different but that is not tested by me. My installation is on Debian, headless .. 

1. Make sure that this is in the path in sonarr
/usr/bin/nodejs
2. Make sure that this is in the argument field:
/home/dennis/Telegram/notification.js
(of course change the paths to your installation)
I think it is possible to remove from arguments to the path, but did not try that one yet.

3. Not sure why I am using nodejs rather than node, but I believe it is the same

4. now you do save, but if you do this, you have half way ! cause testing will fail and now comes the silly part

5. in my experience with 2 custom scripts (this one and the shell one I have running) you need to save the 'connect' settings where  all the connect tiles are, if you do not do this: sonarr will not start the new added custom script and you will not see output in the log even if you use trace.

So the script we have been testing monday is still working and in my Telegram I still get info from the shell script (orig idea) and the node js script with all the info ..

**Comment by aroundmyroom** [comment]
I got my chatID as follows
send a message to the bot
than
 curl -i -X GET https://api.telegram.org/bot[TOKEN]/getUpdates
than you will get the info

**Comment by jayrox** [comment]
i was thinking about adding another command for the bot to reply with the current chat id to make it as simple as possible for the end user.

**Comment by aroundmyroom** [comment]
very good id. I was searching for a long time how to do it cause the guidelines do forget many times that you only get a valid responsive if there is a message sent to the bot.

**Comment by jayrox** [comment]
In my testing i found the "Test" button in Sonarr's Custom Script setup it appears to be a placebo button that does nothing. So hitting it and expecting the log files to actually show details is a waste of time, unfortunately several hours of troubleshooting for me.

To get the notify script to work for me on Windows, I had to set the path to the full path to node `C:\Program Files\nodejs\node.exe` and the full path to `sonarr_notify.js` in the Arguments field. As seen here: http://i.imgur.com/CmA5Mkx.png

Hitting `Test` did nothing but hitting Save on the config and Save again on the settings got it into a workable state.

**Comment by aroundmyroom** [comment]
The test button only validates the existence of the path and file, it is not running it (found that answer on the sonarr forum (this is the behaviour of the custom script parth in sonarr

**Comment by jayrox** [comment]
Yeah, I saw that too but I don't believe it. For example, when I changed `sonarr_notify.js` to  `s0n4rr_n0t1fy.js` it still said the test passed.

**Comment by aroundmyroom** [comment]
I was following this thread .. 
https://forums.sonarr.tv/t/custom-scripts-not-executing-on-synology/9049/2
but I believe it is only checking if there exist a path
but does not matter, we have a working environment (Windows & Linux) yeah ! ;-)

**Comment by jayrox** [comment]
Yep. It works perfectly for me now.

**Comment by aroundmyroom** [comment]
any update in the pull? ;-)

**Comment by onedr0p** [comment]
I can merge the branch @jayrox you think it's good enough to merge?

**Comment by jayrox** [comment]
yeah, i've been running for a few days now and i've not had any issues. still needs some documentation to setup but for now, it works and should be fine to commit. possibly need a command to get a group chat id. `/gid` or something.

i'd also like to add some subscription like features to it possibly. doubt everyone wants to get notified for each and every addition but could add a `/sub [title]` command to get some subset of notifications would be nice.

**Comment by jayrox** [comment]
* added `/cid` to help get the current chat id. the `/cid` command is a `owner` command and can only be ran by the id listed as the bot `owner`.
* added textual documentation for setting up the notifications.
* i've started looking at a basic notification subscription model `/sub [title]` and `/unsub [title]` for use with subset notifications as the current model is all or nothing. however, sonarr does currently have some filtering with the setup of the custom script. that can be used for the time being.

at this point i believe the notification stuff is ready for prod and a pr has been submitted. @onedr0p if you want to have a look at it, feel free to merge or add anything i may have missed.
