### ISSUE TITLE
Notify issue 

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#38]
Documentation is incorrect
Readme.md

* Open a new chat or group chat with the bot and type `/cid`
* Note the Chat ID
* Open `config.js` and enter the Chat ID next to `notifyId`
* Restart the bot
* The specified chat will now begin receiving notifications for newly added content

there is no config.js, there is a config.json but there is no notifyId
I have a 'owner' configured which is same as my chatID

**Comment by jayrox** [comment]
You shouldnt run `node sonarr_notify` it isn't meant to run on its own as a
bot.

Sonarr just runs it as a script. I'll get the `config.js` part fixed when I
get back to my computer.

**Comment by aroundmyroom** [comment]
See it in the config.json.example
but is it true that owner = chatid ?

**Comment by aroundmyroom** [comment]
Update
it's working
but damn what a little info .. and damn . .I have my Size back !! yeah !!

**Comment by jayrox** [comment]
I plan on adding all of the possible sonarr vars and just allow the bot owner to comment/uncomment the ones they want to see. at least until there is some sort of demand for a config in the bot to handle it.

owner is your telegram user id, which would be the same id in the acl.json. this gives you, as the owner, the ability to run the more restricted commands.

**Comment by aroundmyroom** [comment]
ah ok and in my situation I am the only one .. so .. same id ..

**Comment by jayrox** [comment]
yeah, same id
