### ISSUE TITLE
Show Episodes of shows in Telegram

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#39]
Does the API of Sonarr allow to request what episodes of a show are already available?
ie. I have a show Vinyl and I want to know if there is already some episode downloaded. 

possible?

**Comment by aroundmyroom** [comment]
ie through
https://github.com/Sonarr/Sonarr/wiki/EpisodeFile

**Comment by jayrox** [comment]
based on your link, it looks totally possible.

**Comment by aroundmyroom** [comment]
maybe an idea like
/q vinyl 
answer: series already exist and being tracked: 
files available: xx

**Comment by onedr0p** [comment]
Yep looks like it can be done, we may also need to write a function that can send multiple messages in order. since the response would be a lot of episodes. This would also be used in the query for all the shows in the sonarr library.

**Comment by aroundmyroom** [comment]
kewl. Episode file would be sufficient to return. no path no other info necessary (i think).

**Comment by jayrox** [comment]
We can reuse the setInterval code I used to send the library. Would just
need to refactor it out to accept a chat id to send the message to and an
array containing the stuff to send.

**Comment by aroundmyroom** [comment]
any update on this one? ;-)

**Comment by jayrox** [comment]
Not yet, some shows have hundreds or even thousands (Sesame Street) of
episodes and sending them all would be quite a bit overwhelming. How would
that be handled without breaking the bot or pissing off Telegram.

**Comment by aroundmyroom** [comment]
ahahahah .. .;-) cut it down by the season folders if that is possible .. (custom keyboard) and when selecting the keyboard return what is in that season folder ..  ?

**Comment by onedr0p** [comment]
Closing issue, while this would be nice... I don't think spamming the user with episodes is important and kind of isn't the point of the bot (which is to add content)
