### ISSUE TITLE
Users whitelist

### ISSUE THREAD

**Issue by subzero79** [onedr0p/telegram-sonarr-bot#4]
As seen in the CP bot, add the ability to the bot to respond only to certain chat_id or usernames.

**Comment by onedr0p** [comment]
This will be tricky for sure. I was thinking about adding a user defined admin command set via config.json that would allow you to add or remove chat_ids/usernames. Implementation might be a little rough.

**Comment by subzero79** [comment]
For bash i had this line to avoid replying to any other user than myself

```
        if [ $OFFSET != 1 ] && [ $SENDER = $TARGET ] ; then
                case $MESSAGE in
                        '/info') msg="This is bashbot, the Telegram bot written entirely in bash.";;
                        '/latest_grabbed') latest_grabbed ; msg=$echo_grabbed;;
                        '/latest_imported') latest_imported ; msg=$echo_imported;;
```

SENDER is .message.chat.id and TARGET is my chat_id. Probably you can use username nickname also

**Comment by onedr0p** [comment]
Right this would make sense and easy to implement just making it work for one person. I have around 7 people I let use these bots. It's not feasible to ask them all to give me their user ids or ask them to make their Telegram account public.

With that said I will add a section in the config file for adding userid/usernames to an array and update the code to only send to those if filled it.

**Comment by bybeet** [comment]
Here's my idea for an initial implementation of a user whitelist.

Whitelisted UserIds are stored in a file alongside the configuration file. Upon startup, the bot reads the file and stores all valid user ids in a list. The bot would only need to check for a whitelisted user when the `/query` command is sent.

To make it easy for people to manage, a password is set via the configuration file. This password can be used in combination with a new `/authenticate` command. When the bot receives `/authenticate` with the proper password it writes out the Telegram UserId to a whitelisted users file. Then the whitelisted users are reloaded. This approach would not need a specified admin, require people to find/know their UserId, or need a bot restart for additional users.

Thoughts/opinions/suggestions?

**Comment by onedr0p** [comment]
That's a really good idea. I really like the idea to authenticate with a password, it makes the most sense.

Given this list, we might need a way for the admin of the bot to delete userIds. We can think of this in the future with another password/command.

If i understand correctly:

`acl.json`
```json
{
  "allowedUsers": [] // list of allowed userIds
}
```

new `config.json`
```json
{
  "telegram": {
    "botToken": "",
    "password": "" // password for authentication 
  },
  "sonarr": {
    "hostname": "",
    "apiKey": "",
    "port": 8989,
    "urlBase": "",
    "ssl": false,
    "username": "",
    "password": ""
  }
}
```

I really like this!

**Comment by bybeet** [comment]
Great. I'll move forward with this approach in the couchpotato bot.

**Comment by jayrox** [comment]
I think I have something for this issue. I'll submit some code that I think will do the trick.

**Comment by onedr0p** [comment]
added in v0.1.8
