### ISSUE TITLE
Take Var Message out of sonarr_notify.js

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#40]
the var message is part of the sonarr_notify.js but if you change this newer commits wont' be pulled by it

Updating d434e91..545ac7b
error: Your local changes to the following files would be overwritten by merge:
        sonarr_notify.js

**Comment by jayrox** [comment]
Yea, I'm not sure the best way to handle this. Do we create a template file that works similar to the config.json.template files and just tell it to ignore the changes to the notify file? I don't expect the users to be well versed in node.js, javascript, json or any other programming language to know how to fix it themselves. I also don't expect the sonarr_notify.js to be used by many people. I see it more as a "nice to have" than a "must have". 

I dont know, maybe a template file will work. I'll give it some thought. For now, I would make a copy of the sonarr_notify.js file outside of the directory, as a backup of sorts. Then do the merge and copy it back. Then again, depending on your version, you may want the newer copy.

What do you guys think on how we should handle this?

**Comment by aroundmyroom** [comment]
if, by default my settings will be used I have never an issue anymore ;-)
but maybe you can put some stuff it in the config.json template what can be defined would be less troublesome

I will test this afternoon / tonight (I am CET+1)
what the default settings are with some extra's .. 
if that gives me what I need ;-)

**Comment by aroundmyroom** [comment]
found a typewriting error

line 52: qualityversion is typed incorrectly

message.push('*Quality Version:* ' + qualtiyversion);

**Comment by jayrox** [comment]
fixed the spelling mistake

**Comment by aroundmyroom** [comment]
this is an nice default
message.push('*Episode Imported*');
message.push(series_title + ' - ' + season + 'x' + episode);
message.push('*TVDB ID:* ' + series_tvdbid);
message.push('*Air Date:* ' + airdate);
message.push('*Quality:* ' + quality);
message.push('*Size:* ' + fileSizeInMegaBytes + ' MB');
message.push('*Destination:* ' + target);

**Comment by jayrox** [comment]
This is how I have mine, simply because I didnt want it sending a ton of lines to the chat.


```
Episode Imported
Title - SeasonxEpisode
AirDate - Quality - Size MB
```
