### ISSUE TITLE
problem adding shows

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#54]
latest version
trying to add a new show
Sonarr is telling me that it is actually adding a series, but .. 
Adding Series [305574][The Crown] Path: [/media/usenet/TV/The Crown]

it is never added

when I manually add it in sonarr: totally no issue.

Has the poster part broken anything, how to debug?

seems related to this

https://forums.sonarr.tv/t/sonarr-having-issues-adding-series-requested-from-other-programs/11497/10

any chance that the latest update broke something previously was working?

**Comment by aroundmyroom** [comment]
16-10-3 17:30:48.1|Info|SeriesService|Adding Series [305574][The Crown] Path: [/media/usenet/TV/The Crown]
16-10-3 17:30:48.1|Trace|Owin|SQLite error (1299): abort at 47 in [INSERT INTO [Series] ([TvdbId],[TvRageId],[TvMazeId],[ImdbId],[Title],[CleanTitle],[SortTitle],[Status],[Overview],[AirTime],[Monitored],[ProfileId],[SeasonFolder],[LastInfoSync],[Runtime],[Ima

16-10-3 17:30:48.1|Trace|NzbDroneErrorPipeline|Handling Exception
16-10-3 17:30:48.1|Trace|Http|Res: 393 [POST] /api/series: 409.Conflict (213 ms)
16-10-3 17:30:48.1|Debug|Api|[POST] /api/series: 409.Conflict (213 ms)

**Comment by onedr0p** [comment]
Looks like there might have been a change in Sonarrs API. I will have to take a further look when I have time.

**Comment by samwiseg00** [comment]
Having the same issue. My trace is the same.

16-10-5 00:28:58.2|Info|SeriesService|Adding Series [74995][Cosmos] Path: [/tv-shows/Cosmos]
16-10-5 00:28:58.2|Trace|Owin|
16-10-5 00:28:58.2|Trace|Owin|SQLite error (1299): abort at 47 in [INSERT INTO [Series] ([TvdbId],[TvRageId],[TvMazeId],[ImdbId],[Title],[CleanTitle],[SortTitle],[Status],[Overview],[AirTime],[Monitored],[ProfileId],[SeasonFolder],[LastInfoSync],[Runtime],[Ima

16-10-5 00:28:58.2|Trace|NzbDroneErrorPipeline|Handling Exception
16-10-5 00:28:58.2|Trace|Http|Res: 147 [POST] /api/series: 409.Conflict (51 ms)
16-10-5 00:28:58.2|Debug|Api|[POST] /api/series: 409.Conflict (51 ms)
16-10-5 00:29:12.3|Trace|Scheduler|Pending Tasks: 0

**Comment by gr4z** [comment]
+1 same here

**Comment by TheCannings** [comment]
Also having this issue

**Comment by onedr0p** [comment]
this is fixed, i would shutdown the bot, and run `git pull` in the project directory and start the bot again.

**Comment by aroundmyroom** [comment]
great .. tested it and 'the crown' as example has been added in Sonarr now !

**Comment by samwiseg00** [comment]
+1
