### ISSUE TITLE
For what's worth: native Telegram support Sonarr available

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#60]
Although with less features
Sonarr has native Telegram support for notifications now. Not as much features as this, but it is available now.
since: 
2.0.0.4411 - Dec 1 2016

**Comment by schumi2004** [comment]
I still prefer telegram's bot notifications, only thing missing for me is tvrage ID usage

**Comment by aroundmyroom** [comment]
I see that what Sonarr is offering me is all I need to know, I have used all information, but all I use is source and title .. and that is what is offered. enough for me.
