### ISSUE TITLE
Point to a different project

### ISSUE THREAD

**Issue by alcmoraes** [onedr0p/telegram-sonarr-bot#65]
Hi @onedr0p , how are you? Hope you're fine!

I'm currently working on another project that works with both Sonarr and Radarr. Would you be willing to point out as an alternative to your project in your `Readme.md`?

https://github.com/alcmoraes/gramarr

Thanks in advance!

**Comment by onedr0p** [comment]
yeet! you wrote it in Go! I've been slowly learning Go myself. 

I'll be sure to link this project, I should probably archive my projects as they are probably extremely out of date with the telegram API.
